coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    project:
      default:
        target: 90%
        threshold: 1%
    patch:
      default:
        target: 90%
        threshold: 1%

flags:
  unit:
    paths:
      - src/
    carryforward: true

ignore:
  - "tests/**/*"
  - "docs/**/*"
  - "**/*.d.ts"

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false
